import 'package:flutter/cupertino.dart';
import 'package:flutter_news/part1/RecentPage.dart';
import 'package:flutter_news/part2/contents2/SmallVideoPage.dart';
import 'package:flutter_news/part2/contents2/HomeListPage.dart';

List<Widget> tabPageList = [
  // RecentPage(),
  HomeListPage(),
  Center(child: Text('头条')),
  Center(child: Text('视频')),
  Center(child: Text('娱乐')),
  Center(child: Text('轻松一刻')),
  Center(child: Text('收藏')),
  Center(child: Text('卡包')),
  Center(child: Text('抖音')),
  Center(child: Text('分享')),
  Center(child: Text('设置')),
  Center(child: Text('军事')),
  Center(child: Text('英雄联盟')),
  Center(child: Text('地区')),
  Center(child: Text('支付')),
  Center(child: Text('发现')),
  Center(child: Text('微信')),
  Center(child: Text('知乎')),
  Center(child: Text('火山')),
  Center(child: Text('卡包')),
  Center(child: Text('生活')),
  Center(child: Text('热点')),
  Center(child: Text('房产')),
  Center(child: Text('股票')),
  Center(child: Text('历史')),
  Center(child: Text('家居')),
  Center(child: Text('独家')),
];

List<Widget> videoTabData = [
  Center(child: Text('榜单')),
  SmallVideoPage(),
  Center(child: Text('头条')),
  Center(child: Text('搞笑')),
  Center(child: Text('新闻')),
  Center(child: Text('影视')),
  Center(child: Text('综艺')),
  Center(child: Text('音乐')),
  Center(child: Text('小品')),
  Center(child: Text('军事')),
  Center(child: Text('体育')),
  Center(child: Text('二次元')),
  Center(child: Text('科幻')),
  Center(child: Text('纪录片')),
  Center(child: Text('萌物')),
];

List<String> videoTabsLabels = [
  '榜单',
  'MAIN',
  '头条',
  '搞笑',
  '新闻',
  '影视',
  '综艺',
  '音乐',
  '小品',
  '军事',
  '体育',
  '二次元',
  '科幻',
  '纪录片',
  '萌物',
];
